### ISSUE TITLE
View Queries Fail with: "Exception occurred: java.lang.NullPointerException"

### ISSUE THREAD

**Issue by averigin** [mapd/mapd-core#61] opened 2017-08-25 16:30 UTC
I'm using MapD 3.2.0 and have created a view based on the results of a `LEFT JOIN`. E.g.:
```
CREATE VIEW joined_view AS (
SELECT
  table1.*,
  table2.somethingElse
FROM
  Table1 AS table1
LEFT JOIN
  Table2 AS table2
ON
  table1.stringValue = table2.stringValue
);
```
Both `stringValue` columns used in the join are `TEXT ENCODING DICT(32)`.

The view is created successfully. I create an Immerse dashboard from the view containing a map (based on GPS data from `Table1`) and a bar chart (record counts based on the `somethingElse` column from `Table2`). This works as expected... for a little while.

After browsing and filtering (by selecting things on the bar chart) for a little while (10s - 5min) an error dialog pops up stating:
```
Exception: Exception occurred: java.lang.NullPointerException
```
If I try to reload the dashboard, an error dialog states: `FAILED TO LOAD DASHBOARD`.
If I try to run a basic query against the view from the `mapdql` CLI, it fails with the above NPE error message.

I found this in `$MAPD_DATA/mapd_log/log4j.log`:
```
2017-08-25 15:25:02 ERROR CalciteException:<init>:59 - org.apache.calcite.sql.validate.SqlValidatorException: Object 'Table1' not found
2017-08-25 15:25:02 ERROR CalciteException:<init>:61 - org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 15: Object 'Table1' not found
2017-08-25 15:25:02 ERROR CalciteServerHandler:process:108 - Exception occurred: java.lang.NullPointerException
```
However, I am still able to directly query `Table1`.

If I recreate the view, everything starts working again, but eventually the same error occurs.

**Comment by asuhan** [comment] 2017-08-25 18:11
@dwayneberry you might want to have a look.

**Comment by dwayneberry** [comment] 2017-08-31 23:56
@averigin I have tried to identify the issue you are seeing and currently cannot get any error to occur.

i built a similar dashboard to what you described above using the default 10K flights dataset joined to a table with state name and state abbreviations

```
create view flights_join as select flights.*,abbr.name statename from flights_2008_10k as flights left join state_abbr as abbr on flights.dest_state = abbr.abbr;
```
The state_abbr is
```
create table state_abbr (name text,abbr text);
INSERT INTO state_abbr VALUES ('NORTH CAROLINA','NC');
INSERT INTO state_abbr VALUES ('NORTH DAKOTA','ND');
INSERT INTO state_abbr VALUES ('OHIO','OH');
INSERT INTO state_abbr VALUES ('OKLAHOMA','OK');
INSERT INTO state_abbr VALUES ('SOUTH DAKOTA','SD');
INSERT INTO state_abbr VALUES ('TENNESSEE','TN');
INSERT INTO state_abbr VALUES ('TEXAS','TX');
INSERT INTO state_abbr VALUES ('UTAH','UT');
INSERT INTO state_abbr VALUES ('WISCONSIN','WI');
INSERT INTO state_abbr VALUES ('WYOMING','WY');
INSERT INTO state_abbr VALUES ('OREGON','OR');
INSERT INTO state_abbr VALUES ('PENNSYLVANIA','PA');
INSERT INTO state_abbr VALUES ('RHODE ISLAND','RI');
INSERT INTO state_abbr VALUES ('SOUTH CAROLINA','SC');
INSERT INTO state_abbr VALUES ('VERMONT','VT');
INSERT INTO state_abbr VALUES ('VIRGINIA','VA');
INSERT INTO state_abbr VALUES ('WASHINGTON','WA');
INSERT INTO state_abbr VALUES ('WEST VIRGINIA','WV');
INSERT INTO state_abbr VALUES ('ALABAMA','AL');
INSERT INTO state_abbr VALUES ('ALASKA','AK');
INSERT INTO state_abbr VALUES ('ARIZONA','AZ');
INSERT INTO state_abbr VALUES ('ARKANSAS','AR');
INSERT INTO state_abbr VALUES ('FLORIDA','FL');
INSERT INTO state_abbr VALUES ('GEORGIA','GA');
INSERT INTO state_abbr VALUES ('HAWAII','HI');
INSERT INTO state_abbr VALUES ('IDAHO','ID');
INSERT INTO state_abbr VALUES ('KENTUCKY','KY');
INSERT INTO state_abbr VALUES ('LOUISIANA','LA');
INSERT INTO state_abbr VALUES ('MAINE','ME');
INSERT INTO state_abbr VALUES ('MARYLAND','MD');
INSERT INTO state_abbr VALUES ('MISSOURI','MO');
INSERT INTO state_abbr VALUES ('MONTANA','MT');
INSERT INTO state_abbr VALUES ('NEBRASKA','NE');
INSERT INTO state_abbr VALUES ('NEVADA','NV');
INSERT INTO state_abbr VALUES ('CALIFORNIA','CA');
INSERT INTO state_abbr VALUES ('COLORADO','CO');
INSERT INTO state_abbr VALUES ('CONNECTICUT','CT');
INSERT INTO state_abbr VALUES ('DELAWARE','DE');
INSERT INTO state_abbr VALUES ('ILLINOIS','IL');
INSERT INTO state_abbr VALUES ('INDIANA','IN');
INSERT INTO state_abbr VALUES ('IOWA','IA');
INSERT INTO state_abbr VALUES ('KANSAS','KS');
INSERT INTO state_abbr VALUES ('MASSACHUSETTS','MA');
INSERT INTO state_abbr VALUES ('MICHIGAN','MI');
INSERT INTO state_abbr VALUES ('MINNESOTA','MN');
INSERT INTO state_abbr VALUES ('MISSISSIPPI','MS');
INSERT INTO state_abbr VALUES ('NEW HAMPSHIRE','NH');
INSERT INTO state_abbr VALUES ('NEW JERSEY','NJ');
INSERT INTO state_abbr VALUES ('NEW MEXICO','NM');
INSERT INTO state_abbr VALUES ('NEW YORK','NY');
```
Can you reproduce on this simple set up?

I will need some further information from you and logs and data if you can share.

**Comment by averigin** [comment] 2017-09-01 22:01
I think I've figured out a way to reproduce the problem:

  1. Import the flight data and state abbreviations into a database and create a view from these (as outline above).
  2. Create a dashboard based off of the view from 1 (point map of `dest_lat` & `dest_lon`, bar chart of `dest_city` by record count).
  3. Create a second database and import the flight data into a table in this database.
  4. Create a dashboard based off of the table from 3 (same charts as the other dashboard).
  5. Open both dashboards (i.e., in separate browser tabs) and move both maps in quick succession. (Sometime I have to bound back and forth between them a couple times).

I have found that this reliably causes the view's dashboard to that failing with this error in my browser's JavaScript console:
```
on move event redrawall error: Error: Exception: Exception occurred: java.lang.NullPointerException
...
```

Hope it doesn't just work on my machine...

**Comment by dwayneberry** [comment] 2017-09-11 20:28
@averigin 

When you say ```2. Create a second database and import the flight data into a table in this database.``` i am assuming you mean ```create database mydb```, not meaning start another instance of MapD running?

Can you please confirm.

**Comment by averigin** [comment] 2017-09-11 20:45
Correct: it's 2 databases running within a single `mapd_server` process.

**Comment by dwayneberry** [comment] 2017-09-11 20:51
@averigin I cannot reproduce this issue internally.  I know there was one fix related to this area but that was before v3.2.0.  Could you please upgrade to v3.2.2 and see if you can reproduce with the simple scenario.
If you can still reproduce the error still, please send me a copy of the mapd_server.INFO log

**Comment by averigin** [comment] 2017-09-22 20:52
I finally got around to testing this today and was still able to reproduce the error. Here's the [`mapd_server.INFO`](https://github.com/mapd/mapd-core/files/1325819/mapd_server.INFO.txt) log.

**Comment by randyzwitch** [comment] 2018-08-31 20:51
Closing this issue. If this still persists using one of our current 4.x releases, please feel free to file a new issue or start a conversation at https://community.mapd.com/

**Closed by randyzwitch** 2018-08-31 20:51 UTC
